import axios, { AxiosError } from "axios";

export const API_TOKEN_STORAGE_KEY = "manga_auth_token";

export const API_BASE_URL =
  process.env.NEXT_PUBLIC_API_BASE_URL?.replace(/\/$/, "") ??
  "http://localhost:8000/api/v1";

export const api = axios.create({
  baseURL: API_BASE_URL,
  timeout: 20000,
  headers: {
    "Content-Type": "application/json",
  },
});

api.interceptors.request.use((config) => {
  if (typeof window !== "undefined") {
    const token = window.localStorage.getItem(API_TOKEN_STORAGE_KEY);
    if (token) {
      config.headers.Authorization = `Bearer ${token}`;
    }
  }

  // Khi body là FormData, xóa Content-Type để browser tự set
  // multipart/form-data; boundary=<auto-generated>
  if (config.data instanceof FormData) {
    delete config.headers["Content-Type"];
  }

  return config;
});

export function compactParams<T extends object>(params?: T) {
  if (!params) return undefined;

  return Object.fromEntries(
    Object.entries(params as Record<string, unknown>).filter(([, value]) => value !== undefined && value !== null && value !== ""),
  );
}

export function getApiErrorMessage(error: unknown): string {
  if (axios.isAxiosError(error)) {
    const axiosError = error as AxiosError<{ detail?: string; message?: string }>;
    const detail = axiosError.response?.data?.detail ?? axiosError.response?.data?.message;
    if (detail) return detail;
    if (axiosError.code === "ECONNABORTED") return "Request timed out. Backend co the dang ban.";
    return axiosError.message;
  }

  if (error instanceof Error) return error.message;
  return "Co loi khong xac dinh xay ra.";
}
